name = "jcc-web-mvp"
compatibility_date = "2026-06-18"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "jcc_web_new"
database_id = "b63a038f-b778-40cf-8539-a220f3a8b87c"
